import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FundaGram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.topnav}>
          <Link href="/"><a>Home</a></Link>
          <Link href="/Profile"><a>Profile</a></Link>
        </div>
        <div className={styles.feed}>
        </div>
      </main>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
